default_language_version:
  python: python3
exclude: 'media'
ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: 'monthly'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-yaml
    - id: check-toml
    - id: check-json
      exclude: |
        (?x)^(
          .devcontainer/.*devcontainer\.json$
        )$
    - id: check-byte-order-marker
      exclude: .gitignore
    - id: check-merge-conflict
    - id: detect-private-key
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
  - repo: local
    hooks:
      - id: lint
        name: linting and formatting
        entry: "lint.sh"
        language: python
        types: [python]
        require_serial: true
        verbose: true
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "ans,linar,nam,tread,ot,assertIn,dependin,socio-economic"]
