name: Simple CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure all your requirements are listed in requirements.txt
          # Example (installing manually):
          pip install -r requirements.txt
          pip install selenium pytest-asyncio pytest requests aiohttp

      # 4. Copy Sample Configs to Config Directory (Adjust as needed)
      - name: Copy Sample Configs
        run: |
          mkdir -p my_digital_being/config
          cp my_digital_being/config_sample/*.json my_digital_being/config/

      # 5. Set Dummy API Keys in Config Files (Adjust if needed)
      - name: Set Dummy API Keys
        run: |
          sed -i 's/"COMPOSIO_API_KEY": ".*"/"COMPOSIO_API_KEY": ""/' my_digital_being/config/character_config.json
          sed -i 's/"LITELLM_API_KEY": ".*"/"LITELLM_API_KEY": ""/' my_digital_being/config/skills_config.json
          sed -i 's/"OPENAI_API_KEY": ".*"/"OPENAI_API_KEY": ""/' my_digital_being/config/skills_config.json
          sed -i 's/"TWITTER_API_KEY": ".*"/"TWITTER_API_KEY": ""/' my_digital_being/config/skills_config.json

      # 6. Install Chrome and Chromedriver
      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Remove or replace existing chromedriver symlink, if any
          if [ -L /usr/bin/chromedriver ]; then
            sudo rm /usr/bin/chromedriver
          elif [ -e /usr/bin/chromedriver ]; then
            sudo rm /usr/bin/chromedriver
          fi
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      # 7. Set Environment Variables for Testing
      - name: Set Environment Variables
        run: echo "COMPOSIO_API_KEY=dummy_value" >> $GITHUB_ENV

      # 8. Run Tests
      - name: Run Tests
        run: |
          pytest tests/ --maxfail=5 --disable-warnings
